name: main

on:
  push:
    branches: [ master, develop, feature/*, release/* ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          submodules: true

      - name: JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build
        run: ./gradlew clean assemble
